[project]
name = "ai-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "dharaniraj1514", email = "dharaniraj1514@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "easyocr>=1.7.2",
    "numpy>=2.5.3",
    "opencv-python>=5.0.0.93",
    "rapidfuzz>=3.14.6",
]

[project.scripts]
ai-service = "ai_service:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
